### ISSUE TITLE
CreateAccountHappyPath

### ISSUE THREAD

**Issue by BartoszDybczak** [BartoszDybczak/SeleniumMyStoreAutomation#20]
https://github.com/BartoszDybczak/SeleniumMyStoreAutomation/blob/814b7c387b806a3226bcd2d6f535dc45c2e4895b/src/test/java/CreateAccount/CreateAccountHappyPath.java#L1-L74

**Comment by KrzyZajac** [comment]
Looks ok from selenium point of view. But I am curious if logic of the tests could not be better. I mean in many assertions you verify the text just after it is typed into field.
If there is something like summary screen after submitting, it would be better to verify if all the data is correct after it is submitted.
