### ISSUE TITLE
HomePageTests

### ISSUE THREAD

**Issue by BartoszDybczak** [BartoszDybczak/SeleniumMyStoreAutomation#22]
https://github.com/BartoszDybczak/SeleniumMyStoreAutomation/blob/814b7c387b806a3226bcd2d6f535dc45c2e4895b/src/test/java/HomePage/HomePageTests.java#L1-L89

**Comment by KrzyZajac** [comment]
Name of the method "userCanSeeContactNumber()" suggests that you verify if contact number is displayed, while you verify if it is correct.

**Comment by KrzyZajac** [comment]
Name of the method "userCanClickOnItemCard()" suggests something else that is done inside- you check if price is correct

**Comment by KrzyZajac** [comment]
And 2 general thoughts:
1. Just like in tests of registration page- is there a possibility to verify if data is correct after submitting it?
2. Each test opens new instance of Home Page. It is good when you look at tests independence. But it may cause poor performance of tests. Maybe there is a way to run all tests on one page? Eventually to refresh before next test? It may be faster I think.
