### ISSUE TITLE
PlacerOrderTest

### ISSUE THREAD

**Issue by BartoszDybczak** [BartoszDybczak/SeleniumMyStoreAutomation#26]
https://github.com/BartoszDybczak/SeleniumMyStoreAutomation/blob/814b7c387b806a3226bcd2d6f535dc45c2e4895b/src/test/java/PlaceOrder/PlaceOrderTest.java#L1-L56

**Comment by KrzyZajac** [comment]
I see you use user data in more than one place. Maybe it is worth to create a file with user data and just import them where needed?
