### ISSUE TITLE
BasePageObject

### ISSUE THREAD

**Issue by BartoszDybczak** [BartoszDybczak/SeleniumMyStoreAutomation#6]
https://github.com/BartoszDybczak/SeleniumMyStoreAutomation/blob/814b7c387b806a3226bcd2d6f535dc45c2e4895b/src/main/java/com/automationpractice/myproject/pages/BasePageObject.java#L1-L179

**Comment by KrzyZajac** [comment]
I see empty curly braces in lines 95 and 96. Is it correct?

**Comment by BartoszDybczak** [comment]
> I see empty curly braces in lines 94 and 95. Is it correct?

There should've been  e.printStackTrace(). I added it @KrzyZajac
